Test branch
KIU-GEDGADA/EosEngine pull request #45
Opened 2022-05-01 13:37 UTC by DoMa157

2022-05-02 08:18 UTC, memory-hunter approved these changes
looking good

2022-05-02 08:44 UTC, DerWaschbar requested changes

2022-05-02 08:44 UTC, DerWaschbar commented on src/main/java/math/MatrixHelper.java
> +package math;
Why is this change in test PR?

2022-05-02 08:44 UTC, DerWaschbar commented on src/main/java/math/Transform.java
> +package math;
Why is this change in test PR?

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Matrix4x4Test.java
> +    });
Create `@beforeAll` init function and put all initialization there. It's important to make sure that one test does not change input data and affect others.

~~~
@beforeAll
void init() {
  ....
  }
  ~~~

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Matrix4x4Test.java
> +    void multiply(){
```suggestion
    void testMultiply(){
```

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Matrix4x4Test.java
> +    void transpose(){
```suggestion
    void testTranspose(){
```

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Matrix4x4Test.java
> +    void setIdentity(){
```suggestion
    void testSetIdentity(){
```

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Matrix4x4Test.java
> +public class Matrix4x4Test {
`Matrix4x4` has other methods too, like - `zero`, `setCell` `negate` and others. Add tests for all of them.

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Vector4fTest.java
> +    Vector4f v2 = new Vector4f(3,3,3,3);
Should be init function as well.

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Vector4fTest.java
> +    void normalize(){
```suggestion
    void testNormalize(){
```

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Vector3fTest.java
> +    Vector3f v3 = new Vector3f(2,2,1);
Should be in init method!

2022-05-02 08:44 UTC, DerWaschbar commented on src/test/java/math/Vector3fTest.java
> +public class Vector3fTest {
What about other methods? Add tests for more of them.

Test method names should include 'test' in them.

2022-05-10 06:23 UTC, DerWaschbar requested changes

2022-05-10 06:23 UTC, DerWaschbar commented on src/main/java/math/Matrix4x4.java
> +                    }
??????

2022-05-10 06:23 UTC, DerWaschbar commented on src/main/java/math/Matrix4x4.java
> +                    }
Clean up if condition's statement. Remove if not necessary or implement the body.

2022-05-10 06:23 UTC, DerWaschbar commented on src/main/java/math/Matrix4x4.java
> +                    }
Fix & Merge, do not wait for my review, teammates can approve it.

2022-05-16 14:27 UTC, memory-hunter approved these changes
Looking good, fixes have been made and tests pass

2022-05-16 15:08 UTC, DerWaschbar approved these changes

2022-05-16 15:09 UTC, merged